language: cpp
sudo: required
dist: trusty
os:
  - linux
compiler:
  - clang
  - gcc
matrix:
  allow_failures:
  - os: osx
  fast_finish: true
before_install:
  - sudo bash .travis/before_install
script: .travis/build
