language: cpp
os:
  - linux
compiler:
  - clang
  - gcc
matrix:
  fast_finish: true
addons:
  apt:
    packages:
    - autotools-dev
    - autoconf-archive
    - libgtk-3-dev
    - libpcsclite-dev
    - libtool
    - automake
    - autoconf
    - libcurl4-openssl-dev
    - libxml2-dev
    - libproxy-dev
    - pkg-config
    - libp11-kit-dev
    - libassuan-dev
    - libgpg-error-dev
script:
  - .travis/build
